FROM {{ parent }}
LABEL MAINTAINER="Rasmus Munk <rasmus.munk@nbi.ku.dk>"
ARG PACKAGE_TIMEOUT=60

USER root

# Setup default timeout of installing packages
RUN echo "[global]" > /etc/pip.conf \
    && echo "timeout=$PACKAGE_TIMEOUT" >> /etc/pip.conf

RUN apt-get update \
    && apt-get install -yq --no-install-recommends \
    pkg-config \
    gmsh \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -fr /tmp/tmp*

WORKDIR /tmp
USER $NB_UID

ENV PKG_CONFIG_PATH=$PYTHON3_PATH/lib/pkgconfig

RUN conda config --set remote_read_timeout_secs $PACKAGE_TIMEOUT

# Clone the python3 enviornment into fenicsx to enable the installation
# of two seperate fenics installations, namely the old fenics and the new fenicsx
RUN mamba create --name fenics
ENV FENICS_PATH=$CONDA_DIR/envs/fenics

COPY environment.yml /tmp/
RUN mamba env update -n fenics -f /tmp/environment.yml \
    && mamba clean --all -f -y \
    && fix-permissions $CONDA_DIR \
    && fix-permissions /home/$NB_USER

COPY requirements.txt /tmp/
RUN mamba run -n fenics pip install -r /tmp/requirements.txt \
    && mamba clean --all -f -y \
    && fix-permissions $CONDA_DIR \
    && fix-permissions /home/$NB_USER
# Add the fenicsx kernel to Jupyter
RUN mamba run -n fenics python -m ipykernel install --user --name=fenics

ENV FIREDRAKE_PATH=/opt/firedrake
USER root
RUN apt-get update \
    && curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install \
    && echo "y" | mamba run -n python3 python3 /tmp/firedrake-install --venv-name ${FIREDRAKE_PATH} --disable-ssh --no-vtk --minimal-petsc \
    && fix-permissions ${FIREDRAKE_PATH} \
    && fix-permissions /home/$NB_USER

USER $NB_UID

COPY requirements-firedrake.txt /tmp/
RUN ${FIREDRAKE_PATH}/bin/pip3 install -r /tmp/requirements-firedrake.txt \
    && ${FIREDRAKE_PATH}/bin/python3 -m ipykernel install --user --name=firedrake

# # Ensure that the pkg config can be found in in the Jupyter kernels
RUN mamba run -n python3 python3 /usr/local/bin/update_kernel_spec.py python3 --env-kwargs PATH=$PYTHON3_PATH/bin:$PATH \
    && mamba run -n fenics python3 /usr/local/bin/update_kernel_spec.py fenics --env-kwargs PATH=$FENICS_PATH/bin:$PATH \
    && ${FIREDRAKE_PATH}/bin/python3 /usr/local/bin/update_kernel_spec.py firedrake --env-kwargs PATH=$FIREDRAKE_PATH/bin:$PATH

WORKDIR "${HOME}"

# Ensure that container Runs as
USER $NB_UID