FROM nielsbohr/r-notebook:edge
COPY tests /app/tests

WORKDIR /app/tests

RUN pip install pytest \
    && pip install -r requirements.txt

USER root

RUN chown $NB_USER:$NB_GID -R notebooks \
    && chmod +x test.sh

# Run container as
USER $NB_USER

CMD ["bin/bash"]
ENTRYPOINT ["/app/tests/test.sh"]
