FROM nielsbohr/r-notebook:edge
COPY tests /app/tests

WORKDIR /app/tests

RUN pip install pytest \
    && pip install -r requirements.txt

USER root

RUN chown jovyan:users -R notebooks \
    && chmod +x test.sh

# Run container as
USER jovyan

CMD ["bin/bash"]
ENTRYPOINT ["/app/tests/test.sh"]
