FROM {{ parent }}
LABEL MAINTAINER="Rasmus Munk <rasmus.munk@nbi.ku.dk>"
ARG PACKAGE_TIMEOUT=60

USER root

# Setup default timeout of installing packages
RUN echo "[global]" > /etc/pip.conf \
    && echo "timeout=$PACKAGE_TIMEOUT" >> /etc/pip.conf

# Install xcms
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    libnetcdf-dev \
    libc6-dev-i386 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# NOTE: install extras directly from github and CRAN as requested in erda ticket #18198
# IMPORTANT: R defaults to unpack with non-existant /bin/gtar so we overrride
ENV TAR="/bin/tar"

# install r packages
RUN mamba install -yq -n r \
    'r-FactoMineR' \
    'r-factoextra' \
    && mamba clean --all -f -y \
    && /opt/conda/envs/r/bin/R -e 'IRkernel::installspec()' \
    && fix-permissions $CONDA_DIR \
    && fix-permissions /home/$NB_USER

COPY ./res /opt/res
RUN mamba run -n r $R_PATH/bin/Rscript /opt/res/*.R

RUN mamba install -yq -n r \
    'r-magick' \
    && mamba clean --all -f -y \
    && /opt/conda/envs/r/bin/R -e 'IRkernel::installspec()' \
    && fix-permissions $CONDA_DIR \
    && fix-permissions /home/$NB_USER

WORKDIR "${HOME}"

# Run container as
USER $NB_UID
