name: bio-bigdata-notebook
dependencies:
  - r-FactoMineR
  - r-factoextra
  - r-magick
  - r-remotes
  - r-circlize
  - r-ggplot2
  - r-pheatmap
  - r-plyr
  - r-plotly
  - r-phytools
  - r-dplyr
  - r-tidyr
  - r-magrittr
  - r-gridExtra
  - r-corpcor
  - r-rmarkdown
  - r-tinytex
  - r-biocmanager
channels:
  - conda-forge