FROM nielsbohr/base-notebook:edge
COPY tests /app/tests

WORKDIR /app/tests

# base pip is for pip3
RUN pip install pytest \
    && pip install -r requirements.txt

USER root

RUN chmod +x test.sh

# Run container as
USER $NB_UID

CMD ["bin/bash"]
ENTRYPOINT ["/app/tests/test.sh"]
