FROM {{ parent }}
LABEL MAINTAINER="Rasmus Munk <rasmus.munk@nbi.ku.dk>"
ARG PACKAGE_TIMEOUT=60

USER root

RUN apt-get update \
	&& apt-get install -yq dotnet6 \
	&& apt-get clean \
	&& rm -fr /var/lib/apt/lists/*

USER $NB_USER

RUN dotnet tool install -g Microsoft.Quantum.IQSharp \
	&& $HOME/.dotnet/tools/dotnet-iqsharp install --user

WORKDIR "${HOME}"

# Ensure that container Runs as
USER $NB_UID
