FROM {{ parent }}
LABEL MAINTAINER="Rasmus Munk <rasmus.munk@nbi.ku.dk>"
ARG PACKAGE_TIMEOUT=60

WORKDIR /tmp

COPY requirements.txt /tmp/
RUN mamba run -n python3 pip install -r /tmp/requirements.txt

WORKDIR "${HOME}"

# Ensure that container Runs as
USER $NB_UID
