FROM nielsbohr/statistics-notebook:edge
COPY tests /app/tests

WORKDIR /app/tests

# Install dependencies for testing environment(s)
RUN jupyterlab_pip install pytest \
    && jupyterlab_pip install -r requirements.txt

USER root

RUN chown $NB_UID:$NB_GID -R notebooks \
    && chmod +x test.sh \
    && chown $NB_UID:$NB_GID -R /app/tests

# pytest barfs on utf8 character in leaflet.py without any encoding header as
# e.g. the apostrophe in don't in line 409, which is not the ascii char (').
# Prepend encoding header to the file until it is solved upstream.
RUN sed -i '1i\# -*- coding: utf-8 -*-' /opt/conda/envs/python*/lib/python*/site-packages/ipyleaflet/leaflet.py

# Run container as
USER $NB_UID

CMD ["bin/bash"]
ENTRYPOINT ["/app/tests/test.sh"]
