FROM nielsbohr/tomography-notebook:edge
COPY tests /app/tests

WORKDIR /app/tests

RUN $PYTHON3_PATH/bin/pip install pytest \
    && $PYTHON3_PATH/bin/pip install -r requirements.txt

# hpy5 tests requires unittest2
RUN $PYTHON2_PATH/bin/pip install unittest2

USER root

RUN chown $NB_UID:$NB_GID -R notebooks \
    && chmod +x test.sh \
    && chown $NB_UID:$NB_GID -R /app/tests

# Run container as
USER $NB_UID

CMD ["bin/bash"]
ENTRYPOINT ["/app/tests/test.sh"]
