FROM {{ parent }}
LABEL MAINTAINER="Rasmus Munk <rasmus.munk@nbi.ku.dk>"
ARG PACKAGE_TIMEOUT=60

USER root

{{ extra_template }}

USER root

# Add the NVIDIA HPC Compiler
RUN echo 'deb [trusted=yes] https://developer.download.nvidia.com/hpc-sdk/ubuntu/amd64 /' | tee /etc/apt/sources.list.d/nvhpc.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    nvhpc-{{ nvhpc_version_major }}-{{ nvhpc_version_minor }}-cuda-multi \
    && apt-get clean \
    && rm -fr /var/lib/apt/lists/*

# Setup the Nvidia HPC Compiler environment vars
ENV NVHPC="{{ nvhome }}"
ENV NVHPC_ROOT="{{ nvhome }}/{{ target }}/{{ nvhpc_version_major }}.{{ nvhpc_version_minor }}"
ENV PATH="{{ nvcompdir }}/extras/qd/bin:{{ nvcompdir }}/bin:{{ nvcudadir }}/bin:$PATH"

ENV LD_LIBRARY_PATH="{{ nvcommdir }}/nvshmem/lib:{{ nvcommdir }}/nccl/lib:{{ nvmathdir }}/lib64:{{ nvcompdir }}/lib:{{ nvcompdir }}/extras/qd/lib:{{ nvcudadir }}/extras/CUPTI/lib64:{{ nvcudadir }}/lib64"
ENV CPATH="{{ nvcompdir }}/extras/qd/include/qd:{{ nvcommdir }}/nvshmem/include:{{ nvcommdir }}/nccl/include:{{ nvmathdir }}/include"
ENV MANPATH="{{ nvcompdir }}/man"


WORKDIR "${HOME}"

# As an exception, run as root,
# Remember to use supervisord start-notebook.sh to
# de-escalate privileges to $NB_UID:$NB_GID
USER root
