FROM {{ parent }}
LABEL MAINTAINER="Rasmus Munk <rasmus.munk@nbi.ku.dk>"
ARG PACKAGE_TIMEOUT=60

USER root

# Setup default timeout of installing packages
RUN echo "[global]" > /etc/pip.conf \
    && echo "timeout=$PACKAGE_TIMEOUT" >> /etc/pip.conf

# Dep
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    libboost-filesystem-dev \
    libboost-serialization-dev \
    libboost-regex-dev \
    libboost-program-options-dev \
    zlib1g-dev \
    libsigsegv-dev \
    freeglut3 \
    freeglut3-dev \
    libxmu-dev \
    libxi-dev \
    libhdf5-dev \
    libhdf5-doc \
    libjson-c-dev \
    libnetcdf-dev \
    libnetcdff-dev \
    libnetcdff-doc \
    environment-modules \
    tcl \
    procps \
    clang-12 \
    llvm-12 \
    libomp5-12 \
    libomp-12-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp

RUN mkdir -p /opt \
    && chgrp $NB_GID /opt \
    && chmod 774 /opt

# Launch script
RUN echo "#!/usr/bin/env bash" > /usr/local/bin/hpc_launch.sh && \
    echo "set -e" >> /usr/local/bin/hpc_launch.sh && \
    echo "cd /home" >> /usr/local/bin/hpc_launch.sh && \
    echo "git clone https://github.com/ucphhpc/hpc_course.git /opt/hpc_course" >> /usr/local/bin/hpc_launch.sh && \
    echo "chgrp -R $NB_GID /opt/hpc_course" >> /usr/local/bin/hpc_launch.sh && \
    echo "chmod -R g+w /opt/hpc_course" >> /usr/local/bin/hpc_launch.sh
RUN chmod a+x /usr/local/bin/hpc_launch.sh

COPY supervisord.conf /etc/supervisor/hpc-supervisord.conf
RUN cat /etc/supervisor/hpc-supervisord.conf >> /etc/supervisor/supervisord.conf \
    && rm -fr /etc/supervisor/hpc-supervisord.conf

USER $NB_UID

RUN conda config --set remote_read_timeout_secs $PACKAGE_TIMEOUT

COPY environment.yml /tmp/
RUN conda env update -n python3 -f environment.yml \
    && conda clean --all -f -y \
    && fix-permissions $CONDA_DIR \
    && fix-permissions /home/$NB_USER

COPY requirements.txt /tmp/
RUN conda run -n python3 pip install -r requirements.txt \
    && conda clean -y --all \
    && fix-permissions $CONDA_DIR \
    && fix-permissions /home/$NB_USER

WORKDIR /home/$NB_USER

ENV PATH="$PATH:$HOME/.local/bin"

# As an exception, run as root,
# Remember to use supervisord start-notebook.sh to
# de-escalate privileges to $NB_UID:$NB_GID
USER root
