FROM {{ parent }}
LABEL MAINTAINER="Rasmus Munk <rasmus.munk@nbi.ku.dk>"
ARG PACKAGE_TIMEOUT=60

USER root

# Setup default timeout of installing packages
RUN echo "[global]" > /etc/pip.conf \
    && echo "timeout=$PACKAGE_TIMEOUT" >> /etc/pip.conf

# R-studio envs provided by r-notebook
# BioBase dependency
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    libxml2-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp

USER $NB_UID

RUN conda config --set remote_read_timeout_secs $PACKAGE_TIMEOUT

# Standard CRAN packages, etc.
COPY environment.yml /tmp/
RUN mamba env update -q -n r -f /tmp/environment.yml \
    && mamba clean --all -f -y \
    && /opt/conda/envs/r/bin/R -e 'IRkernel::installspec()' \
    && fix-permissions $CONDA_DIR \
    && fix-permissions /home/$NB_USER

# Removed 'cutadapt' via conda  for now and moved it to pypi installation
# via the requirements.txt file. This is because the current version does not support
# Python 3.11 (https://bioconda.github.io/recipes/cutadapt/README.html)
COPY requirements.txt /tmp/
RUN mamba run -n r pip install -r /tmp/requirements.txt \
    && mamba clean --all -f -y \
    && fix-permissions $CONDA_DIR \
    && fix-permissions /home/$NB_USER

COPY requirements.txt /tmp/
RUN mamba run -n r pip install -r requirements.txt \
    && mamba clean --all -f -y \
    && fix-permissions $CONDA_DIR \
    && fix-permissions /home/$NB_USER

ENV PATH="$R_PATH/bin:$PATH"

# NOTE: install BioConductor packages requested e.g. in erda ticket #18198 and #25320
# NOTE: install extras directly from github and CRAN as requested in erda ticket #18198
# IMPORTANT: R defaults to unpack with non-existant /bin/gtar so we overrride
ENV TAR="/bin/tar"
# install tmp r packages
COPY ./res /opt/res
RUN mamba run -n r $R_PATH/bin/Rscript /opt/res/*.R

WORKDIR "${HOME}"

# Run container as
USER $NB_UID
