FROM {{ parent }}
LABEL MAINTAINER="Rasmus Munk <rasmus.munk@nbi.ku.dk>"
ARG PACKAGE_TIMEOUT=60

WORKDIR /tmp

COPY requirements.txt /tmp/
RUN mamba run -n python3 pip install -r /tmp/requirements.txt \
    && mamba clean -y --all \
    && fix-permissions $CONDA_DIR \
    && fix-permissions /home/$NB_USER

WORKDIR "${HOME}"

# Run container as
USER $NB_UID
