OWNER = "nielsbohr"
LATEST_TAG = "latest"

BASE_NOTEBOOK = "base-notebook"
PYTHON_NOTEBOOK = "python-notebook"
R_NOTEBOOK = "r-notebook"
SLURM_NOTEBOOK = "slurm-notebook"
PYTHON_CUDA_NOTEBOOK = "python-cuda-notebook"
GPU_NOTEBOOK = "gpu-notebook"
DGX1_NOTEBOOK = "dgx1-notebook"
DATASCIENCE_NOTEBOOK = "datascience-notebook"
CHEMISTRY_NOTEBOOK = "chemistry-notebook"
FENICS_NOTEBOOK = "fenics-notebook"
QSHARP_NOTEBOOK = "qsharp-notebook"
STATISTICS_NOTEBOOK = "statistics-notebook"
TOMOGRAPHY_NOTEBOOK = "tomography-notebook"
HPC_NOTEBOOK = "hpc-notebook"
HPC_OCEAN_NOTEBOOK = "hpc-ocean-notebook"
OCEAN_NOTEBOOK = "ocean-notebook"
GEO_NOTEBOOK = "geo-notebook"
BIO_NOTEBOOK = "bio-notebook"
BIO_BIGDATA_NOTEBOOK = "bio-bigdata-notebook"
BIO_BSA_NOTEBOOK = "bio-bio-bsa-notebook"
SME_NOTEBOOK = "sme-notebook"
JWST_NOTEBOOK = "jwst-notebook"

NOTEBOOKS = [
    BASE_NOTEBOOK,
    PYTHON_NOTEBOOK,
    R_NOTEBOOK,
    SLURM_NOTEBOOK,
    PYTHON_CUDA_NOTEBOOK,
    GPU_NOTEBOOK,
    DGX1_NOTEBOOK,
    DATASCIENCE_NOTEBOOK,
    CHEMISTRY_NOTEBOOK,
    FENICS_NOTEBOOK,
    QSHARP_NOTEBOOK,
    STATISTICS_NOTEBOOK,
    TOMOGRAPHY_NOTEBOOK,
    HPC_NOTEBOOK,
    HPC_OCEAN_NOTEBOOK,
    OCEAN_NOTEBOOK,
    GEO_NOTEBOOK,
    BIO_NOTEBOOK,
    BIO_BIGDATA_NOTEBOOK,
    BIO_BSA_NOTEBOOK,
    SME_NOTEBOOK,
    JWST_NOTEBOOK
]

BASE_NOTEBOOK_LATEST = "{}:{}".format(BASE_NOTEBOOK, LATEST_TAG)
PYTHON_NOTEBOOK_LATEST = "{}:{}".format(PYTHON_NOTEBOOK, LATEST_TAG)
R_NOTEBOOK_LATEST = "{}:{}".format(R_NOTEBOOK, LATEST_TAG)

SLURM_NOTEBOOK_LATEST = "{}:{}".format(SLURM_NOTEBOOK, LATEST_TAG)
SLURM_NOTEBOOK_20_02_07 = "{}:{}".format(SLURM_NOTEBOOK, "20.02.07")
SLURM_NOTEBOOK_21_08_0 = "{}:{}".format(SLURM_NOTEBOOK, "21.08.0")

PYTHON_CUDA_NOTEBOOK_LATEST = "{}:{}".format(PYTHON_CUDA_NOTEBOOK, LATEST_TAG)
GPU_NOTEBOOK_LATEST = "{}:{}".format(GPU_NOTEBOOK, LATEST_TAG)
DGX1_NOTEBOOK_LATEST = "{}:{}".format(DGX1_NOTEBOOK, LATEST_TAG)
DATASCIENCE_NOTEBOOK_LATEST = "{}:{}".format(DATASCIENCE_NOTEBOOK, LATEST_TAG)
CHEMISTRY_NOTEBOOK_LATEST = "{}:{}".format(CHEMISTRY_NOTEBOOK, LATEST_TAG)
FENICS_NOTEBOOK_LATEST = "{}:{}".format(FENICS_NOTEBOOK, LATEST_TAG)
QSHARP_NOTEBOOK_LATEST = "{}:{}".format(QSHARP_NOTEBOOK, LATEST_TAG)
STATISTICS_NOTEBOOK_LATEST = "{}:{}".format(STATISTICS_NOTEBOOK, LATEST_TAG)
TOMOGRAPHY_NOTEBOOK_LATEST = "{}:{}".format(TOMOGRAPHY_NOTEBOOK, LATEST_TAG)

HPC_NOTEBOOK_LATEST = "{}:{}".format(HPC_NOTEBOOK, LATEST_TAG)
HPC_NOTEBOOK_20_02_07 = "{}:{}".format(HPC_NOTEBOOK, "20.02.07")
HPC_NOTEBOOK_21_08_0 = "{}:{}".format(HPC_NOTEBOOK, "21.08.0")

HPC_OCEAN_NOTEBOOK_LATEST = "{}:{}".format(HPC_OCEAN_NOTEBOOK, LATEST_TAG)
HPC_OCEAN_NOTEBOOK_20_02_07 = "{}:{}".format(HPC_NOTEBOOK, "20.02.07")
HPC_OCEAN_NOTEBOOK_21_08_0 = "{}:{}".format(HPC_NOTEBOOK, "21.08.0")

OCEAN_NOTEBOOK_LATEST = "{}:{}".format(OCEAN_NOTEBOOK, LATEST_TAG)
GEO_NOTEBOOK_LATEST = "{}:{}".format(GEO_NOTEBOOK, LATEST_TAG)
BIO_NOTEBOOK_LATEST = "{}:{}".format(BIO_NOTEBOOK, LATEST_TAG)
BIO_BIGDATA_NOTEBOOK_LATEST = "{}:{}".format(BIO_BIGDATA_NOTEBOOK, LATEST_TAG)
BIO_BSA_NOTEBOOK_LATEST = "{}:{}".format(BIO_BSA_NOTEBOOK, LATEST_TAG)
SME_NOTEBOOK_LATEST = "{}:{}".format(SME_NOTEBOOK, LATEST_TAG)
JWST_NOTEBOOK_LATEST = "{}:{}".format(JWST_NOTEBOOK, LATEST_TAG)
