FROM nielsbohr/chemistry-notebook:edge
COPY tests /app/tests

WORKDIR /app/tests

RUN pip install pytest \
    && pip install -r requirements.txt

USER root

RUN chown $NB_UID:$NB_GID -R notebooks \
    && chmod +x test.sh \
    && chown $NB_UID:$NB_GID -R /app/tests

# Run container as
USER $NB_UID

RUN ln -s $PYTHON2_PATH/bin/pytest $CONDA_DIR/bin/pytest

CMD ["bin/bash"]
ENTRYPOINT ["/app/tests/test.sh"]
