FROM {{ parent }}
LABEL MAINTAINER="Rasmus Munk <rasmus.munk@nbi.ku.dk>"
ARG PACKAGE_TIMEOUT=60

USER root

# Setup default timeout of installing packages
RUN echo "[global]" > /etc/pip.conf \
    && echo "timeout=$PACKAGE_TIMEOUT" >> /etc/pip.conf

USER $NB_UID

WORKDIR /tmp

RUN conda config --set remote_read_timeout_secs $PACKAGE_TIMEOUT
ENV PYTHON3_PATH=$CONDA_DIR/envs/python3

RUN mamba create -n python3 python=3.7 \
    && mamba clean --all -f -y \
    && fix-permissions $CONDA_DIR \
    && fix-permissions /home/$NB_USER

# Install diffpy into python2 env
# diffpy also provides pyobjcrust
COPY environment.yml /tmp/
RUN mamba env update -n python3 -f /tmp/environment.yml \
    && mamba run -n python3 python -m ipykernel install --user --name=python3 \
    && mamba clean --all -f -y \
    && fix-permissions $CONDA_DIR \
    && fix-permissions /home/$NB_USER

# Ensure that container Runs as
USER $NB_UID

COPY requirements.txt /tmp/
RUN mamba run -n python3 pip install -r /tmp/requirements.txt \
    && mamba clean --all -f -y \
    && fix-permissions $CONDA_DIR \
    && fix-permissions /home/$NB_USER

# Add the python3 environment to the jupyter kernel path
RUN mamba run -n python3 python3 /usr/local/bin/update_kernel_spec.py python3 --env-kwargs PATH=$PYTHON3_PATH/bin:$PATH

WORKDIR "${HOME}"

# Run container as
USER $NB_UID
